language: node_js
node_js:
  - "node"

services:
  - docker

cache:
  directories:
    - server/node_modules

before_install:
  - ganache-cli --port 18545 > ganache-cli.log &
  - git clone https://github.com/oceanprotocol/barge
  - cd barge
  - bash -x start_ocean.sh --latest --no-secret-store --no-aquarius --no-brizo --no-pleuston --local-spree-node 2>&1 > start_ocean.log &
  - cd ..
  - git clone https://github.com/oceanprotocol/faucet.git
  - cd faucet
  - ./server/scripts/wait_for_migration_and_extract_keeper_artifacts.sh > keeper.log &
  - sleep 60
 # - npm run build > start_faucet.log &
  - docker-compose up > start_faucet.log &
  - sleep 120
  - wget --header="Content-Type: application/json" --post-data '{"address": "0x7E187af69973a66e049a15E763c97CB726765f87", "agent": "twitter"}' http://localhost:3001/faucet
  - cd ..
  - npm install

script:
  - npm test