language: node_js
node_js:
  - "node"

services:
  - docker

cache:
  directories:
    - server/node_modules

before_install:
  - ganache-cli --port 18545 > ganache-cli.log &
  - git clone https://github.com/oceanprotocol/barge
  - cd barge
  - bash -x start_ocean.sh --latest --no-secret-store --no-aquarius --no-brizo --no-pleuston --local-spree-node 2>&1 > start_ocean.log &
  - cd ..
  - git clone https://github.com/oceanprotocol/faucet.git
  - cd faucet
 # - ./server/scripts/wait_for_migration_and_extract_keeper_artifacts.sh > keeper.log &
  - sleep 60
  - docker-compose up > start_faucet.log &
  - sleep 300
  - docker ps
 # - "curl -d '{'address':'0x7f1154cb3d5ec897f7aded7cb2c1bf5d124bc624de7f0f58b25b553185eafc91'}' -H 'Content-Type: application/json' -X POST http://localhost:3001/faucet"
  - cd ..
  - npm install

script:
  - npm test